name: rpc_gen
version: 0.1.2
description: The `rpc_gen` is a builder and generator of RPC (Remote Procedure Call) stub files.
homepage: https://github.com/mezoni/rpc_gen
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:  
  analyzer: ^0.41.2
  build: ^1.6.2
  code_builder: ^3.6.0
  source_gen: ^0.9.10+3
dev_dependencies:
  build_runner: ^1.11.1
  http: ^0.13.0
  pedantic: ^1.10.0
  test: ^1.16.3
